export default {
  SET_USERS: 'SET_USERS',
  SET_LOADED: 'SET_LOADED',
  CHANGE_SORT_ORDER: 'CHANGE_SORT_ORDER',
  SET_FILTER: 'SET_FILTER',
  SET_PAGE: 'SET_PAGE',
  SET_DATE_FROM: 'SET_DATE_FROM',
  SET_DATE_TO: 'SET_DATE_TO',
};
